esphome:
  name: lilygo
  platformio_options:
    # Unless noted otherwise, based on https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/1eb6119fc31fcff7a6bafecb09f4225313859fc5/examples/demo/platformio.ini#L37
    upload_speed: 921600
    monitor_speed: 115200
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
    board_build.arduino.memory_type: qspi_opi
    board_build.flash_size: 16MB
    board_build.flash_mode: qio
    board_build.flash_type: qspi
    board_build.psram_type: opi
    board_build.memory_type: qspi_opi
    board_build.boot_freq: 80m
    platform_packages:
      - "toolchain-riscv32-esp @8.4.0+2021r2-patch5"
    build_flags:  # the first three defines are required for the screen library to function.
      - "-DBOARD_HAS_PSRAM"
      - "-DARDUINO_RUNNING_CORE=0"  # TODO: this conflicts with the value from platformio's idedata, spewing a lot of warnings during the build.
      - "-DARDUINO_EVENT_RUNNING_CORE=0"  # and this too
      # In addition to lilygo's settings:
      # To enable reading logs over USB until `hardware_uart: USB_CDC` support
      # is added to `logger:`, as detailed in <https://github.com/esphome/feature-requests/issues/1906>:
      - "-DARDUINO_USB_MODE=1"
      - "-DARDUINO_USB_CDC_ON_BOOT=1"
  libraries:
    - SPI

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1

  framework:
    type: arduino
    # Just like in <https://community.home-assistant.io/t/enable-usb-cdc-to-log-hello-world-to-esp32-s3-dev-board-for-esphome/463164/10>
    # I had problems with newer versions; the following combination happens to work, so using it for now.
    version: 2.0.3
    platform_version: 5.1.1

logger:
  level: VERBOSE
  # hardware_uart: USB_CDC  # see note about <https://github.com/esphome/feature-requests/issues/1906> above

# Enable Home Assistant API
api:  # Set up a key instead: https://community.home-assistant.io/t/2023-2-esphome-deprecated-api-password-how-to-update-to-encryption-key
  password: !secret api_ota_password

ota:
  platform: esphome
  password: !secret api_ota_password

wifi: !include wifi-secrets.yaml

# Include rounded rectangle component
rounded_rect:

shadow_rect:

button:
  - platform: restart
    name: "${esp_name} Restart"

  - platform: template
    name: "${esp_name} Refresh"
    icon: "mdi:update"

  - platform: template
    name: "${esp_name} Next Page"
    icon: "mdi:update"
    on_press:
      then:
      - display.page.show_next: t5_display
      - component.update: t5_display

binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO21 #was GPIO39 on the previous board
      inverted: true
    name: "Button 1"
    on_press:
      then:
      - display.page.show_next: t5_display
      - component.update: t5_display
  
  - platform: homeassistant
    id: vac_cleaning
    entity_id: binary_sensor.noonoo2_cleaning

sensor:
  - platform: homeassistant
    entity_id: sensor.woonkamer_temperature
    id: woon_temp
    internal: true

  - platform: homeassistant
    entity_id: sensor.woonkamer_humidity
    id: woon_hum
    internal: true
  
  - platform: homeassistant
    entity_id: sensor.kantoor_temperature
    id: kantoor_temp
    internal: true

  - platform: homeassistant
    entity_id: sensor.kantoor_humidity
    id: kantoor_hum
    internal: true
  
  - platform: homeassistant
    entity_id: sensor.iris_en_ruben_huis_outdoor_temperature
    id: outdoor_temp
    internal: true

  - platform: homeassistant
    entity_id: sensor.slaapkamer_temperature
    id: slaapkamer_temp

  - platform: homeassistant
    entity_id: sensor.slaapkamer_humidity
    id: slaapkamer_hum

  - platform: homeassistant
    entity_id: sensor.noonoo2_cleaning_progress
    id: vac_progress
   
  - platform: homeassistant
    entity_id: sensor.prefix_dev_pixi_stars
    id: pixi_stars
  
  - platform: homeassistant
    entity_id: sensor.prefix_dev_rattler_build_stars
    id: rattler_build_stars
  
  - platform: homeassistant
    entity_id: sensor.conda_rattler_stars
    id: rattler_stars

  # Board platform
  - platform: lilygo_t5_47_battery
    id: battery_voltage
    voltage:
      name: "Battery Voltage"

  - platform: template
    name: "Battery Percentage"
    id: battery_percentage
    lambda: |-
      // tweak values in mapping for calibration
      // 4.1 = max voltage
      // 3.3 = min voltage
      float y = (id(battery_voltage).voltage->state - 3.3) * 100.0 / (4.1 - 3.3);
      if (y < 100.0) { return y; } else { return 100.0; };

external_components:
    - source:
        type: local
        path: components/
      components: ["t547", "lilygo_t5_47_battery", "rounded_rect", "shadow_rect"]


font:

  - file: "gfonts://Google+Sans"
    id: font_date
    size: 58
  - file: "gfonts://Google+Sans"
    id: font_time
    size: 105
  - file: "gfonts://Google+Sans"
    id: font_15
    size: 15
  - file: "gfonts://Google+Sans"
    id: font_20 
    size: 20
  - file: "gfonts://Google+Sans"
    id: font_40
    size: 40
  - file: "gfonts://Google+Sans"
    id: font_50
    size: 50
  - file: "gfonts://Google+Sans"
    id: font_60
    size: 60


image: 
  - file: "images/bg.png"
    id: bg_image
  - file: "mdi:thermometer"
    id: thermometer
    resize: 50x50
  - file: "mdi:thermometer-high"
    id: thermometer_high
    resize: 50x50
  - file: "mdi:water-percent"
    id: water_percent
    resize: 50x50
  - file: "mdi:star"
    id: star_icon
    resize: 100x100

time:
  - platform: homeassistant
    id: ntp

display:
  - platform: t547
    id: t5_display
    rotation: 270
    update_interval: 30s
    pages:
      - id: main_page
        lambda: |-
          #define xres 540
          #define yres 960

          //it.image(0, 0, id(bg_image));

          // Battery level indicator with rounded corners
          auto battery_width = id(battery_percentage).state*xres/100;
          esphome::rounded_rect::RoundedRect::draw_rounded_rect(&it, 0, 0, battery_width, 8, 4, COLOR_ON, true);

          // Date and time in rounded container with shadow
          esphome::shadow_rect::ShadowRect::draw_rect_with_shadow(
            &it,
            10, 10,             // x, y
            xres-20, 200,       // width, height
            COLOR_ON,           // main color
            COLOR_ON,           // shadow color  
            -5, 5,               // x_offset, y_offset
            3,                  // thickness
            false               // filled
          );
          it.strftime(xres/2, 10, id(font_date), TextAlign::TOP_CENTER, "%A %b %d", id(ntp).now());
          it.strftime(xres/2, 80, id(font_time), TextAlign::TOP_CENTER, "%H:%M", id(ntp).now());

          // Climate house
          # define climate_house_y 650
          int xoffset = 20;
          esphome::rounded_rect::RoundedRect::draw_rounded_rect_outline(&it, 10, climate_house_y - 5, xres - 20, 60, 20, COLOR_ON, 5);
          it.print(0 + xoffset, climate_house_y, id(font_40), TextAlign::LEFT, "Woon");
          it.image(140 + xoffset, climate_house_y, id(thermometer));
          it.printf(190 + xoffset, climate_house_y, id(font_40), "%.1f °C", id(woon_temp).state);
          it.image(320 + xoffset, climate_house_y, id(water_percent));
          it.printf(370 + xoffset, climate_house_y, id(font_40), "%.1f %%", id(woon_hum).state);

          // Climate office
          # define climate_kantoor_y 720
          esphome::rounded_rect::RoundedRect::draw_rounded_rect_outline(&it, 10, climate_kantoor_y - 5, xres - 20, 60, 20, COLOR_ON, 5);
          it.print(0 + xoffset, climate_kantoor_y, id(font_40), TextAlign::LEFT, "Kantoor");
          it.image(140 + xoffset, climate_kantoor_y, id(thermometer));
          it.printf(190 + xoffset, climate_kantoor_y, id(font_40), "%.1f °C", id(kantoor_temp).state);
          it.image(320 + xoffset, climate_kantoor_y, id(water_percent));
          it.printf(370 + xoffset, climate_kantoor_y, id(font_40), "%.1f %%", id(kantoor_hum).state);

          // Climate slaapkamer
          # define climate_slaapkamer_y 790
          esphome::rounded_rect::RoundedRect::draw_rounded_rect_outline(&it, 10, climate_slaapkamer_y - 5, xres - 20, 60, 20, COLOR_ON, 5);
          it.print(0 + xoffset, climate_slaapkamer_y, id(font_40), TextAlign::LEFT, "Slaap");
          it.image(140 + xoffset, climate_slaapkamer_y, id(thermometer));
          it.printf(190 + xoffset, climate_slaapkamer_y, id(font_40), "%.1f °C", id(slaapkamer_temp).state);
          it.image(320 + xoffset, climate_slaapkamer_y, id(water_percent));
          it.printf(370 + xoffset, climate_slaapkamer_y, id(font_40), "%.1f %%", id(slaapkamer_hum).state);

          // GitHub
          // Pixi stars, with icon
          int box_width = 160;
          int box_height = 190;
          int x_index_pixi = xres/6;
          int y_index_pixi = 230;
          // esphome::rounded_rect::RoundedRect::draw_rounded_rect_outline(&it, x_index_pixi - box_width/2, y_index_pixi, box_width, box_height, 20, COLOR_ON, 5);
          esphome::shadow_rect::ShadowRect::draw_rect_with_shadow(
            &it,
            x_index_pixi - box_width/2, y_index_pixi, // x, y
            box_width, box_height,                     // width, height
            COLOR_ON,                                 // main color
            COLOR_ON,                                 // shadow color  
            -5, 5,                                    // x_offset, y_offset
            3,                                        // thickness
            false                                     // filled
          );
          it.print(x_index_pixi, y_index_pixi + 30, id(font_40), TextAlign::CENTER, "Pixi");
          it.image(x_index_pixi, y_index_pixi + box_height/2, id(star_icon), ImageAlign::CENTER);
          it.printf(x_index_pixi, y_index_pixi + box_height - 30, id(font_40), TextAlign::CENTER, "%.0f", id(pixi_stars).state);

          // Rattler build stars, with icon
          int x_index_rattler_build = xres/2 ;
          int y_index_rattler_build = 230;
          // esphome::rounded_rect::RoundedRect::draw_rounded_rect_outline(&it, x_index_rattler_build - box_width/2, y_index_rattler_build, box_width, box_height, 20, COLOR_ON, 5);
          esphome::shadow_rect::ShadowRect::draw_rect_with_shadow(
            &it,
            x_index_rattler_build - box_width/2, y_index_rattler_build, // x, y
            box_width, box_height,                     // width, height
            COLOR_ON,                                 // main color
            COLOR_ON,                                 // shadow color  
            -5, 5,                                    // x_offset, y_offset
            3,                                        // thickness
            false                                     // filled
          );
          it.print(x_index_rattler_build, y_index_rattler_build + 30, id(font_40), TextAlign::CENTER, "Rattler B");
          it.image(x_index_rattler_build, y_index_rattler_build + box_height/2, id(star_icon), ImageAlign::CENTER);
          it.printf(x_index_rattler_build, y_index_rattler_build + box_height - 30, id(font_40), TextAlign::CENTER, "%.0f", id(rattler_build_stars).state);

          // Rattler stars, with icon
          int x_index_rattler = xres*5/6 ;
          int y_index_rattler = 230;
          // esphome::rounded_rect::RoundedRect::draw_rounded_rect_outline(&it, x_index_rattler - box_width/2, y_index_rattler, box_width, box_height, 20, COLOR_ON, 5);
          esphome::shadow_rect::ShadowRect::draw_rect_with_shadow(
            &it,
            x_index_rattler - box_width/2, y_index_rattler, // x, y
            box_width, box_height,                     // width, height
            COLOR_ON,                                 // main color
            COLOR_ON,                                 // shadow color
            -5, 5,                                    // x_offset, y_offset
            3,                                        // thickness
            false                                     // filled
          );
          it.print(x_index_rattler, y_index_rattler + 30, id(font_40), TextAlign::CENTER, "Rattler");
          it.image(x_index_rattler, y_index_rattler + box_height/2, id(star_icon), ImageAlign::CENTER);
          it.printf(x_index_rattler, y_index_rattler + box_height - 30, id(font_40), TextAlign::CENTER, "%.0f", id(rattler_stars).state);

          // Vacuum progress bar
          int vac_width = 50;
          int vac_height = 18;
          int vac_spacing = 6;

          /// Draw dock
          int dock_width = 30;
          int dock_height = 50;
          int dock_x = xres - dock_width;
          int dock_y = yres - dock_height - 4;
          it.filled_rectangle(dock_x, dock_y, dock_width, dock_height);
          it.filled_rectangle(dock_x, yres-vac_height-vac_spacing-5, dock_width - 10, vac_height + vac_spacing*2, COLOR_OFF);

          // Draw vacuum state
          if (id(vac_cleaning).state) {
            int vac_state = id(vac_progress).state;
            int vac_pose = vac_state*xres/100;

            // Draw dirt line
            it.filled_rectangle(vac_pose, yres-4, xres, 10);

            // Draw rectangle that represents the Vacuum itself, fitting between the xres and yres limits
            it.filled_rectangle(vac_pose - vac_width / 2, yres - vac_height - vac_spacing, vac_width, vac_height);
            it.filled_rectangle(vac_pose, yres - vac_height - vac_spacing - 4, 10, 4);

            // Draw percentage in vacuum
            it.printf(vac_pose, yres - vac_height - vac_spacing, id(font_15), Color(0, 0, 0), display::TextAlign::TOP_CENTER, "%.0f%%", id(vac_progress).state);
          }
          else {
            // Draw rectangle that represents the Vacuum itself, fitting between the xres and yres limits
            it.filled_rectangle(xres - vac_width - 12, yres - vac_height - vac_spacing, vac_width, vac_height);
            it.filled_rectangle(xres - vac_width - 12 + 10, yres - vac_height - vac_spacing - 4, 10, 4);
          }


      - id: stats
        lambda: |-
          it.printf(10, 50, id(font_20), "Battery: %.1f% (%.1fV)", id(battery_percentage).state, id(battery_voltage).voltage->state);
